# Generated by Django 3.1.4 on 2020-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoClipLibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcevideo',
            old_name='video',
            new_name='filename',
        ),
        migrations.AlterField(
            model_name='markedtimestamp',
            name='video_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
